import { StyleSheet, Dimensions } from 'react-native';
const screenHeight = Dimensions.get('window').height;

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    map: {
        flex: 7,
    },
    instructions: {
        position: 'absolute',
        bottom: 20,
        left: 10,
        right: 10,
        backgroundColor: '#1E1E1E',
        padding: 10,
        borderRadius: 5,
    },
    heading: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
        marginBottom: 5,
    },
    currentStep: {
        color: 'white',
        fontSize: 14,
        marginTop: 5,
    },
    toggleText: {
        color: 'blue',
        fontSize: 14,
        textAlign: 'center',
        marginVertical: 5,
    },
    fullStepsContainer: {
        marginTop: 10,
    },
    fullStep: {
        fontSize: 12,
        marginBottom: 5,
    },
    recenterButton: {
        position: 'absolute',
        top: 40,
        right: 15,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        padding: 10,
        borderRadius: 5,
    },
    menu: {
        position: 'absolute',
        top: 40,
        left: 15,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        padding: 10,
        borderRadius: 5,
    },
    slidingMenu: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        height: '100%',
        backgroundColor: '#FFFFFF',
        padding: 20,
        paddingTop: 40,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 5,
        zIndex: 1000,
    },
    slidingMenuDark: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        height: '100%',
        backgroundColor: '#1E1E1E',
        padding: 20,
        paddingTop: 40,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
        zIndex: 1000,
    },
    closeButton: {
        position: 'absolute',
        top: 10,
        right: 10,
        padding: 10,
        zIndex: 1001,
    },
    menuContent: {
        fontSize: 18,
        color: '#555',
        textAlign: 'center',
    },
    profileSection: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 20,
        paddingHorizontal: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E5E5',
        marginBottom: 20,
    },
    profileText: {
        marginLeft: 15,
        flexShrink: 1,
    },
    profileName: {
        color: '#000000',
        fontSize: 18,
        fontWeight: '600',
        marginBottom: 5,
    },
    profileNameDark: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '600',
        marginBottom: 5,
    },
    viewProfileText: {
        color: '#007AFF',
        fontSize: 14,
    },
    searchContainer: {
        position: 'absolute',
        top: 37,
        left: 80,
        right: 80,
        zIndex: 2,
    },
    searchInput: {
        height: 50,
        backgroundColor: '#ffffff',
        fontSize: 16,
        borderRadius: 12,
        paddingHorizontal: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
    },
    searchList: {
        backgroundColor: '#fff',
        marginHorizontal: -60,
        borderRadius: 12,
        elevation: 2,
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 15,
        paddingHorizontal: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E5E5',
    },
    menuItemDark: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 15,
        paddingHorizontal: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#333333',
    },
    menuItemText: {
        color: '#000000',
        fontSize: 16,
        marginLeft: 15,
        flexShrink: 1,
    },
    menuItemTextDark: {
        color: '#FFFFFF',
        fontSize: 16,
        marginLeft: 15,
        flexShrink: 1,
    },
    instructionsContainer: {
        position: 'absolute',
        bottom: 40,
        left: 20,
        right: 20,
        backgroundColor: '#fff',
        borderRadius: 12,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    instructionsHeader: {
        padding: 15,
    },
    allStepsContainer: {
        maxHeight: 400,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        borderTopWidth: 1,
        borderTopColor: '#eee',
    },
    heading: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 8,
        color: '#333',
    },
    stepRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    stepText: {
        fontSize: 15,
        color: '#333',
        marginLeft: 10,
        flex: 1,
        flexWrap: 'wrap',
    },
    cancelButton: {
        position: 'absolute',
        bottom: 5,
        right: 0,
        backgroundColor: 'red',
        padding: 12,
        borderRadius: 30,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    addEventButton: {
        position: 'absolute',
        bottom:35,
        right: 20,
        backgroundColor: 'white',
        borderRadius: 40,
        padding: 10,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    addEventButtonStepsBar: {
        position: 'absolute',
        bottom:170,
        right: 20,
        backgroundColor: 'white',
        borderRadius: 40,
        padding: 10,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    addEventButtonFullStepsBar: {
        position: 'absolute',
        bottom:570,
        right: 20,
        backgroundColor: 'white',
        borderRadius: 40,
        padding: 10,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    addEventIcon: {
        width: 60,
        height: 60,
        resizeMode: 'contain',
    },
    reportPanel: {
        position: 'absolute',
        bottom: 100,
        left: 20,
        right: 20,
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 16,
        elevation: 5,
    },
    reportHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    reportTitle: {
        fontSize: 18,
        fontWeight: 'bold',
    },
    closeReportPanelButton: {
        fontSize: 25,
        color: 'red',
    },
    reportGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
    },
    reportItem: {
        width: '30%',
        alignItems: 'center',
        marginVertical: 10,
    },
    reportIcon: {
        fontSize: 32,
    },
    reportLabel: {
        marginTop: 4,
        fontSize: 12,
        textAlign: 'center',
    },
    historyButton: {
        position: 'absolute',
        right: 10,
        top: 10,
        backgroundColor: 'white',
        padding: 8,
        borderRadius: 20,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    historyPanel: {
        position: 'absolute',
        top: 60,
        left: 20,
        right: 20,
        backgroundColor: 'white',
        borderRadius: 10,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        maxHeight: 300,
    },
    historyHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    historyTitle: {
        fontSize: 16,
        fontWeight: 'bold',
    },
    closeHistory: {
        fontSize: 20,
        color: '#666',
    },
    historyList: {
        maxHeight: 250,
    },
    historyItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    historyText: {
        marginLeft: 10,
        fontSize: 14,
        color: '#333',
    },
    suggestionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    historySuggestionRow: {
        backgroundColor: '#f8f8f8',
    },
    historyIcon: {
        marginRight: 10,
    },
    suggestionText: {
        fontSize: 14,
        color: '#333',
    },
    historySuggestionText: {
        color: '#666',
    },
    volunteerButton: {
        position: 'absolute',
        left: 20,
        bottom: 30,
        backgroundColor: '#067ef5',
        padding: 20,
        borderRadius: 35,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        width: 70,
        height: 70,
        justifyContent: 'center',
        alignItems: 'center',
    },
    volunteerButtonStepsBar: {
        position: 'absolute',
        left: 20,
        bottom: 170,
        backgroundColor: '#067ef5',
        padding: 20,
        borderRadius: 35,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        width: 70,
        height: 70,
        justifyContent: 'center',
        alignItems: 'center',
    },
    volunteerButtonFullStepsBar: {
        position: 'absolute',
        left: 20,
        bottom: 570,
        backgroundColor: '#067ef5',
        padding: 20,
        borderRadius: 35,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        width: 70,
        height: 70,
        justifyContent: 'center',
        alignItems: 'center',
    },
    volunteerPanel: {
        position: 'absolute',
        left: 20,
        top: 100,
        backgroundColor: 'white',
        padding: 15,
        borderRadius: 10,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        width: 300,
        maxHeight: 470,
    },
    volunteerTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 15,
        color: '#067ef5',
        right: 15,
        textAlign: 'center',
    },
    volunteerReportsList: {
        maxHeight: 900,
    },
    volunteerReportItem: {
        backgroundColor: '#f8f9fa',
        padding: 10,
        borderRadius: 8,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#e9ecef',
    },
    volunteerReportType: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#333',
        marginBottom: 5,
    },
    volunteerReportLocation: {
        fontSize: 14,
        color: '#666',
        marginBottom: 5,
    },
    volunteerReportTime: {
        fontSize: 12,
        color: '#888',
        marginBottom: 10,
    },
    closeVolunteerPanelButton: {
        fontSize: 25,
        color: 'red',
        bottom:38,
        left: 250,
    },
    noReportsText: {
        fontSize: 16,
        color: '#666',
        textAlign: 'center',
        bottom: 1,
    },
    resolveButton: {
        backgroundColor: '#28a745',
        padding: 8,
        borderRadius: 5,
        alignItems: 'center',
    },
    resolveButtonText: {
        color: 'white',
        fontWeight: 'bold',
    },
    debugPanel: {
        position: 'absolute',
        top: 50,
        left: 10,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        padding: 10,
        borderRadius: 8,
        width: 300,
        zIndex: 1000,
    },
    debugTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 8,
        color: '#333',
    },
    debugText: {
        fontSize: 14,
        color: '#333',
        marginBottom: 4,
    },
    offRouteText: {
        color: 'red',
        fontWeight: 'bold',
    },
    debugButton: {
        position: 'absolute',
        top: 10,
        left: 10,
        backgroundColor: '#067ef5',
        padding: 10,
        borderRadius: 5,
        zIndex: 1000,
    },
    debugButtonText: {
        color: 'white',
        fontWeight: 'bold',
    },
    stepItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    currentStepItem: {
        backgroundColor: 'rgba(0, 122, 255, 0.1)',
        borderRadius: 4,
    },
    stepIconContainer: {
        width: 30,
        alignItems: 'center',
        marginRight: 10,
    },
    stepTextContainer: {
        flex: 1,
    },
    stepItemText: {
        fontSize: 14,
        color: '#333',
    },
    stepDistanceText: {
        fontSize: 12,
        color: '#666',
        marginTop: 2,
    },
    etaContainer: {
        backgroundColor: 'rgba(0, 122, 255, 0.1)',
        padding: 8,
        borderRadius: 8,
        marginBottom: 8,
        alignItems: 'center',
    },
    etaText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#007AFF',
    },
});
