import { StyleSheet, Dimensions } from 'react-native';
const screenHeight = Dimensions.get('window').height;

export const styles = StyleSheet.create({
    container: {
        flex: 1,
    },
    map: {
        flex: 7,
    },
    instructions: {
        position: 'absolute',
        bottom: 20,
        left: 10,
        right: 10,
        backgroundColor: '#1E1E1E',
        padding: 10,
        borderRadius: 5,
    },
    heading: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
        marginBottom: 5,
    },
    currentStep: {
        color: 'white',
        fontSize: 14,
        marginTop: 5,
    },
    toggleText: {
        color: 'blue',
        fontSize: 14,
        textAlign: 'center',
        marginVertical: 5,
    },
    fullStepsContainer: {
        marginTop: 10,
    },
    fullStep: {
        fontSize: 12,
        marginBottom: 5,
    },
    recenterButton: {
        position: 'absolute',
        top: 40,
        right: 15,
        backgroundColor: '#FFFFFF',
        padding: 10,
        borderRadius: 12,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    recenterButtonDark: {
        position: 'absolute',
        top: 40,
        right: 15,
        backgroundColor: '#2C2C2E',
        padding: 10,
        borderRadius: 12,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    menu: {
        position: 'absolute',
        top: 40,
        left: 15,
        backgroundColor: '#FFFFFF',
        padding: 10,
        borderRadius: 12,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    menuDark: {
        position: 'absolute',
        top: 40,
        left: 15,
        backgroundColor: '#2C2C2E',
        padding: 10,
        borderRadius: 12,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    slidingMenu: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        height: '100%',
        backgroundColor: '#FFFFFF',
        padding: 20,
        paddingTop: 40,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 5,
        zIndex: 1000,
    },
    slidingMenuDark: {
        position: 'absolute',
        left: 0,
        right: 0,
        bottom: 0,
        height: '100%',
        backgroundColor: '#1E1E1E',
        padding: 20,
        paddingTop: 40,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 5,
        zIndex: 1000,
    },
    closeButton: {
        paddingLeft: 230,
        padding: 5,
    },
    closeButtonIcon: {
        
        fontSize: 33,
        color: '#FF3B30',
    },
    closeButtonIconDark: {
        fontSize: 33,
        color: '#FF453A',
    },
    menuContent: {
        fontSize: 18,
        color: '#555',
        textAlign: 'center',
    },
    profileSection: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 20,
        paddingHorizontal: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E5E5',
        marginBottom: 20,
    },
    profileSectionDark: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 20,
        paddingHorizontal: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#333333',
        marginBottom: 20,
    },
    profileText: {
        marginLeft: 15,
        flexShrink: 1,
    },
    profileName: {
        color: '#000000',
        fontSize: 18,
        fontWeight: '600',
        marginBottom: 5,
    },
    profileNameDark: {
        color: '#FFFFFF',
        fontSize: 18,
        fontWeight: '600',
        marginBottom: 5,
    },
    viewProfileText: {
        color: '#007AFF',
        fontSize: 14,
    },
    viewProfileTextDark: {
        color: '#0A84FF',
        fontSize: 14,
    },
    searchContainer: {
        position: 'absolute',
        top: 37,
        left: 80,
        right: 80,
        zIndex: 2,
    },
    searchInput: {
        height: 50,
        backgroundColor: '#FFFFFF',
        fontSize: 16,
        borderRadius: 12,
        paddingHorizontal: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
        elevation: 3,
        color: '#000000',
    },
    searchInputDark: {
        height: 50,
        backgroundColor: '#2C2C2E',
        fontSize: 16,
        borderRadius: 12,
        paddingHorizontal: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
        elevation: 3,
        color: '#FFFFFF',
        placeholderTextColor: '#8E8E93',
    },
    searchList: {
        backgroundColor: '#FFFFFF',
        marginHorizontal: -60,
        borderRadius: 12,
        elevation: 2,
        marginTop: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 3,
    },
    searchListDark: {
        backgroundColor: '#2C2C2E',
        marginHorizontal: -60,
        borderRadius: 12,
        elevation: 2,
        marginTop: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3,
    },
    menuIconLight: {
        color: '#000000',
    },
    menuIconDark: {
        color: '#FFFFFF',
    },
    recenterIconLight: {
        color: '#000000',
    },
    recenterIconDark: {
        color: '#FFFFFF',
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 15,
        paddingHorizontal: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E5E5',
    },
    menuItemDark: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 15,
        paddingHorizontal: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#333333',
    },
    menuItemText: {
        color: '#000000',
        fontSize: 16,
        marginLeft: 15,
        flexShrink: 1,
    },
    menuItemTextDark: {
        color: '#FFFFFF',
        fontSize: 16,
        marginLeft: 15,
        flexShrink: 1,
    },
    instructionsContainer: {
        position: 'absolute',
        bottom: 40,
        left: 20,
        right: 20,
        backgroundColor: '#fff',
        borderRadius: 12,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    instructionsHeader: {
        padding: 15,
    },
    allStepsContainer: {
        maxHeight: 400,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        borderTopWidth: 1,
        borderTopColor: '#eee',
    },
    heading: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 8,
        color: '#333',
    },
    stepRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    stepText: {
        fontSize: 15,
        color: '#333',
        marginLeft: 10,
        flex: 1,
        flexWrap: 'wrap',
    },
    cancelButton: {
        position: 'absolute',
        bottom: 5,
        right: 0,
        backgroundColor: 'red',
        padding: 12,
        borderRadius: 30,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    addEventButton: {
        position: 'absolute',
        bottom: 50,
        right: 20,
        backgroundColor: 'white',
        borderRadius: 35,
        padding: 8,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    addEventButtonDark: {
        position: 'absolute',
        bottom: 50,
        right: 20,
        backgroundColor: '#2C2C2E',
        borderRadius: 35,
        padding: 8,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    addEventButtonStepsBar: {
        position: 'absolute',
        bottom: 185,
        right: 20,
        backgroundColor: 'white',
        borderRadius: 35,
        padding: 8,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    addEventButtonStepsBarDark: {
        position: 'absolute',
        bottom: 185,
        right: 20,
        backgroundColor: '#2C2C2E',
        borderRadius: 35,
        padding: 8,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    addEventButtonFullStepsBar: {
        position: 'absolute',
        bottom: 585,
        right: 20,
        backgroundColor: 'white',
        borderRadius: 35,
        padding: 8,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    addEventButtonFullStepsBarDark: {
        position: 'absolute',
        bottom: 585,
        right: 20,
        backgroundColor: '#2C2C2E',
        borderRadius: 35,
        padding: 8,
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
    },
    addEventIcon: {
        width: 50,
        height: 50,
        resizeMode: 'contain',
    },
    reportPanel: {
        position: 'absolute',
        right: 20,
        top: 100,
        backgroundColor: '#FFFFFF',
        padding: 15,
        borderRadius: 10,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        width: 300,
        maxHeight: 400,
    },
    reportPanelDark: {
        position: 'absolute',
        right: 20,
        top: 100,
        backgroundColor: '#1E1E1E',
        padding: 15,
        borderRadius: 10,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3.84,
        width: 300,
        maxHeight: 400,
    },
    reportHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        paddingHorizontal: 8,
        paddingTop: 8,
        paddingBottom: 8,
    },
    reportHeaderDark: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 15,
    },
    reportTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#007AFF',
        textAlign: 'center',
    },
    reportTitleDark: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#0A84FF',
        textAlign: 'center',
    },
    closeReportPanelButton: {
        fontSize: 28,
        color: '#FF3B30',
        padding: 5,
    },
    closeReportPanelButtonDark: {
        fontSize: 28,
        color: '#FF453A',
        padding: 5,
    },
    reportGrid: {
        maxHeight: 330,
    },
    reportItem: {
        backgroundColor: '#f8f9fa',
        padding: 10,
        borderRadius: 8,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#e9ecef',
        flexDirection: 'row',
        alignItems: 'center',
    },
    reportItemDark: {
        backgroundColor: '#2D2D2D',
        padding: 10,
        borderRadius: 8,
        marginBottom: 10,
        borderWidth: 1,
        borderColor: '#333333',
        flexDirection: 'row',
        alignItems: 'center',
    },
    reportIcon: {
        width: 30,
        height: 30,
        marginRight: 15,
    },
    reportLabel: {
        fontSize: 16,
        color: '#333',
    },
    reportLabelDark: {
        fontSize: 16,
        color: '#FFFFFF',
    },
    historyButton: {
        position: 'absolute',
        right: 10,
        top: 10,
        backgroundColor: 'white',
        padding: 8,
        borderRadius: 20,
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    historyPanel: {
        position: 'absolute',
        top: 60,
        left: 20,
        right: 20,
        backgroundColor: 'white',
        borderRadius: 10,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        maxHeight: 300,
    },
    historyHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    historyTitle: {
        fontSize: 16,
        fontWeight: 'bold',
    },
    closeHistory: {
        fontSize: 20,
        color: '#666',
    },
    historyList: {
        maxHeight: 250,
    },
    historyItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    historyText: {
        marginLeft: 10,
        fontSize: 14,
        color: '#333',
    },
    suggestionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    historySuggestionRow: {
        backgroundColor: '#f8f8f8',
    },
    historyIcon: {
        marginRight: 10,
    },
    suggestionText: {
        fontSize: 14,
        color: '#333',
    },
    historySuggestionText: {
        color: '#666',
    },
    volunteerButton: {
        position: 'absolute',
        left: 20,
        bottom: 50,
        backgroundColor: '#067ef5',
        padding: 15,
        borderRadius: 35,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        width: 60,
        height: 60,
        justifyContent: 'center',
        alignItems: 'center',
    },
    volunteerButtonStepsBar: {
        position: 'absolute',
        left: 20,
        bottom: 185,
        backgroundColor: '#067ef5',
        padding: 15,
        borderRadius: 35,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        width: 60,
        height: 60,
        justifyContent: 'center',
        alignItems: 'center',
    },
    volunteerButtonFullStepsBar: {
        position: 'absolute',
        left: 20,
        bottom: 585,
        backgroundColor: '#067ef5',
        padding: 15,
        borderRadius: 35,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        width: 60,
        height: 60,
        justifyContent: 'center',
        alignItems: 'center',
    },
    volunteerPanel: {
        position: 'absolute',
        left: 20,
        top: 100,
        backgroundColor: '#FFFFFF',
        padding: 15,
        borderRadius: 10,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        width: 300,
        maxHeight: 400,
    },
    volunteerPanelDark: {
        position: 'absolute',
        left: 20,
        top: 100,
        backgroundColor: '#1E1E1E',
        padding: 15,
        borderRadius: 10,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 3.84,
        width: 300,
        maxHeight: 400,
    },
    volunteerTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#007AFF',
        textAlign: 'center',
    },
    volunteerTitleDark: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#0A84FF',
        textAlign: 'center',
    },
    volunteerReportsList: {
        maxHeight: 330,
    },
    volunteerReportItem: {
        backgroundColor: '#FFFFFF',
        padding: 15,
        borderRadius: 8,
        marginBottom: 10,
        borderLeftWidth: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    volunteerReportItemDark: {
        backgroundColor: '#2D2D2D',
        padding: 15,
        borderRadius: 8,
        marginBottom: 10,
        borderLeftWidth: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 2,
    },
    volunteerReportType: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 8,
    },
    volunteerReportTypeDark: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 8,
    },
    volunteerReportLocation: {
        fontSize: 14,
        color: '#666666',
        marginBottom: 4,
    },
    volunteerReportLocationDark: {
        fontSize: 14,
        color: '#B0B0B0',
        marginBottom: 4,
    },
    volunteerReportDistance: {
        fontSize: 14,
        color: '#666666',
        marginBottom: 4,
    },
    volunteerReportDistanceDark: {
        fontSize: 14,
        color: '#B0B0B0',
        marginBottom: 4,
    },
    volunteerReportTime: {
        fontSize: 14,
        color: '#666666',
        marginBottom: 12,
    },
    volunteerReportTimeDark: {
        fontSize: 14,
        color: '#B0B0B0',
        marginBottom: 12,
    },
    buttonContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 8,
    },
    checkDetailsButton: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
        flex: 1,
        marginRight: 8,
    },
    checkDetailsButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    resolveButton: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
        backgroundColor: '#34C759',
        flex: 1,
        marginLeft: 8,
    },
    resolveButtonDark: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 8,
        backgroundColor: '#32D74B',
        flex: 1,
        marginLeft: 8,
    },
    resolveButtonText: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    resolveButtonTextDark: {
        color: '#FFFFFF',
        fontSize: 14,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    noReportsText: {
        textAlign: 'center',
        color: '#666666',
        fontSize: 16,
        marginTop: 20,
    },
    noReportsTextDark: {
        textAlign: 'center',
        color: '#B0B0B0',
        fontSize: 16,
        marginTop: 20,
    },
    debugPanel: {
        position: 'absolute',
        top: 50,
        left: 10,
        backgroundColor: 'rgba(255, 255, 255, 0.9)',
        padding: 10,
        borderRadius: 8,
        width: 300,
        zIndex: 1000,
    },
    debugTitle: {
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 8,
        color: '#333',
    },
    debugText: {
        fontSize: 14,
        color: '#333',
        marginBottom: 4,
    },
    offRouteText: {
        color: 'red',
        fontWeight: 'bold',
    },
    debugButton: {
        position: 'absolute',
        top: 10,
        left: 10,
        backgroundColor: '#067ef5',
        padding: 10,
        borderRadius: 5,
        zIndex: 1000,
    },
    debugButtonText: {
        color: 'white',
        fontWeight: 'bold',
    },
    stepItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    currentStepItem: {
        backgroundColor: 'rgba(0, 122, 255, 0.1)',
        borderRadius: 4,
    },
    stepIconContainer: {
        width: 30,
        alignItems: 'center',
        marginRight: 10,
    },
    stepTextContainer: {
        flex: 1,
    },
    stepItemText: {
        fontSize: 14,
        color: '#333',
    },
    stepDistanceText: {
        fontSize: 12,
        color: '#666',
        marginTop: 2,
    },
    etaContainer: {
        backgroundColor: 'rgba(0, 122, 255, 0.1)',
        padding: 8,
        borderRadius: 8,
        marginBottom: 8,
        alignItems: 'center',
    },
    etaText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#007AFF',
    },
    eventMarker: {
        padding: 5,
        borderRadius: 20,
        backgroundColor: 'white',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    loginButton: {
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 10,
        backgroundColor: '#0A84FF',
        alignSelf: 'flex-start',
        margin: 10
    },
    alertMarker: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: 'rgba(255, 0, 0, 0.3)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    alertMarkerInner: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'red',
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    volunteerHeaderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        paddingHorizontal: 8,
        paddingTop: 8,
        paddingBottom: 8,
    },
});
